spring:
  profiles.active: h2,dev
spring.jmx:
   enabled: false
server:
  port: 8090
  context-path: /${project.name}/
  environment_name: ${cba_environment:dev}
security:
  basic:
    enabled: false
management:
  port: 8091
  context-path: /manage
  security:
    enabled: false
project:
  name: cloud-boot-app
  artifactId: @project.artifactId@
  version: @project.version@
  maintainer: Richard Whitney
logging:
  file: /var/log/${project.name}/${project.name}.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    com.dataservice: DEBUG
    org.hibernate: DEBUG
---

spring.profiles: h2

spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=MySQL
spring.jpa:
    hibernate.ddl-auto: update

---

spring.profiles: mysql

spring.datasource:
  jndi-name: java:comp/env/jdbc/mySqlDataSource
  driverClassName: com.mysql.jdbc.Driver

spring.jpa:
  hibernate:
    dialect: org.hibernate.dialect.MySQLInnoDBDialect
    ddl-auto: update